### PR TITLE
only save leaf nodes in DB, smaller but slower?

### PR DESCRIPTION
**Pull request by landfillbaby**
the updater isn't very pretty but it's the only way i could find to do this
i use substr because it's easier than escaping GLOBs or LIKEs imo

### CODE REVIEW

**Comment by landfillbaby** [comment]
also now only leaf nodes will be output by `whatprovides -p`, but i see this as a good thing personally

**Comment by landfillbaby** [comment]
error message when package not found
choose correctly when to prepend $PREFIX on reverse mode

**Comment by landfillbaby** [comment]
i actually already had a script that made `dpkg -L` do this, only with less robust sorting so a few non-empty directories sometimes get through

**Comment by kcubeterm** [comment]
Used this script to generate files.
https://github.com/termux/whatprovides/blob/ef9c6e68a3e067752fcc9e27f3b4cce6baf8169a/file-gen.sh

**Comment by landfillbaby** [comment]
ok cool :)
also i just realised that we'll need to update the example usage output now

**Comment by kcubeterm** [comment]
I think show usage should be enough for users but anyway nothing wrong in adding few examples. If you want then submit PRs and let's release this version.

**Comment by landfillbaby** [comment]
maybe i should have explained this pull request a bit better, sorry
it fundamentally changed the way this program works
the new usage example, replacing the old one, would be this:
```
$ whatprovides -p aapt
aapt: /data/data/com.termux/files/usr/share/aapt/android.jar
aapt: /data/data/com.termux/files/usr/share/doc/aapt
aapt: /data/data/com.termux/files/usr/lib/libandroid-cutils.so
aapt: /data/data/com.termux/files/usr/lib/libandroid-ziparchive.so
aapt: /data/data/com.termux/files/usr/lib/libandroid-base.so
aapt: /data/data/com.termux/files/usr/lib/libandroid-fw.so
aapt: /data/data/com.termux/files/usr/lib/libandroid-utils.so
aapt: /data/data/com.termux/files/usr/bin/aapt
aapt: /data/data/com.termux/files/usr/bin/zipalign
aapt: /data/data/com.termux/files/usr/share/doc/aapt/LICENSE
```
do you see the difference? all non-empty directories are omitted since their existence is implied by their children

**Comment by landfillbaby** [comment]
if you like i could restore the original output functionality, outputting all parents of files, while keeping the database as i have made it
but honestly i personally prefer it this way, as i have been using a similar wrapper for `dpkg -L` output for years
i hope i've explained this well

**Comment by kcubeterm** [comment]
> if you like i could restore the original output functionality

Naa, it's fine though, no need to revert.

**Comment by landfillbaby** [comment]
ok cool :)
again just in case i was unclear though, this only changes the `-p` output, i took special care to make sure the file search output stays the same

**Pull request merged**
